# languages.py

QUALITY_MAP = {
    "English": ["Highly Compatible (MP4 - 1080p Max)", "Audio Only (MP3)"],
    "Български": ["Висока съвместимост (MP4 - Макс 1080p)", "Само аудио (MP3)"],
    "Русский": ["Высокая совместимость (MP4 - Макс 1080p)", "Только аудио (MP3)"],
    "Français": ["Haute compatibilité (MP4 - 1080p Max)", "Audio uniquement (MP3)"],
    "Italiano": ["Altamente compatibile (MP4 - 1080p Max)", "Solo audio (MP3)"],
    "Deutsch": ["Hohe Kompatibilität (MP4 - Max. 1080p)", "Nur Audio (MP3)"],
    "Español": ["Altamente compatible (MP4 - 1080p Máx)", "Solo audio (MP3)"],
    "日本語": ["高互換性 (MP4 - 最大1080p)", "音声のみ (MP3)"],
    "한국어": ["높은 호환성 (MP4 - 최대 1080p)", "오디오 전용 (MP3)"],
    "简体中文": ["高兼容性 (MP4 - 最高1080p)", "仅音频 (MP3)"],
    "हिन्दी": ["अत्यधिक संगत (MP4 - अधिकतम 1080p)", "केवल ऑडियो (MP3)"]
}

LANGUAGES = {
    "English": {
        "title": "⬇️ YouTube Downloader",
        "subtitle": "Download high-quality videos and audio seamlessly.",
        "url_label": "YouTube URL (Video, Playlist, or Audio):",
        "url_placeholder": "...",
        "paste": "📋 Paste",
        "copy": "📄 Copy",
        "clear": "❌ Clear",
        "autoclear": "Auto-clear URL after successful download",
        "analyze": "Analyze Link",
        "analyzing": "Analyzing...",
        "meta_title": "Video Information",
        "video_title": "Title:",
        "video_channel": "Channel:",
        "video_duration": "Duration:",
        "no_video": "None (Enter a URL and click Analyze)",
        "fetch_failed": "Failed to fetch video details.",
        "fetching": "Fetching details from YouTube...",
        "settings_title": "Download Configuration",
        "ffmpeg_active": "✅ FFmpeg: Active (MP4/MP3 Enabled)",
        "ffmpeg_missing": "❌ FFmpeg: Missing (MP3/MP4 Merging Disabled)",
        "quality_lbl": "Preferred Quality:",
        "destination_lbl": "Save Destination:",
        "browse": "Browse...",
        "playlist_lbl": "Download entire playlist (Enables 10s delay to prevent ban)",
        "show_log_lbl": "Show Live Log Terminal",
        "show_popup_lbl": "Show Popup notification on completion",
        "reset_defaults": "🔄 Reset Defaults",
        "start_download": "⚡ Start Download",
        "downloading": "⏳ Downloading...",
        "pause": "⏸️ Pause",
        "resume": "▶️ Resume",
        "stop": "⏹️ Stop",
        "log_title": "Live Log Terminal:",
        "success_popup_title": "Download Completed",
        "success_popup_msg": "🎉 Success! Media download & conversion completed correctly!"
    },
    "Български": {
        "title": "⬇️ YouTube Свалител",
        "subtitle": "Безпроблемно сваляне на висококачествено видео и аудио.",
        "url_label": "YouTube URL (Видео, Плейлист или Аудио):",
        "url_placeholder": "...",
        "paste": "📋 Постави",
        "copy": "📄 Копирай",
        "clear": "❌ Изчисти",
        "autoclear": "Автоматично изчистване на URL след успешно сваляне",
        "analyze": "Анализирай връзката",
        "analyzing": "Анализиране...",
        "meta_title": "Информация за видеото",
        "video_title": "Заглавие:",
        "video_channel": "Канал:",
        "video_duration": "Времетраене:",
        "no_video": "Няма (Въведете URL и натиснете Анализирай)",
        "fetch_failed": "Неуспешно извличане на детайли.",
        "fetching": "Извличане на детайли от YouTube...",
        "settings_title": "Настройки за сваляне",
        "ffmpeg_active": "✅ FFmpeg: Активен (Разрешено MP4/MP3)",
        "ffmpeg_missing": "❌ FFmpeg: Липсва (Сливането на MP3/MP4 е деактивирано)",
        "quality_lbl": "Предпочитано качество:",
        "destination_lbl": "Папка за запазване:",
        "browse": "Преглед...",
        "playlist_lbl": "Сваляне на целия плейлист (Добавя 10 сек забавяне)",
        "show_log_lbl": "Покажи терминал за жива статистика",
        "show_popup_lbl": "Известие на екрана при завършване",
        "reset_defaults": "🔄 Начални настройки",
        "start_download": "⚡ Свали",
        "downloading": "⏳ Сваляне...",
        "pause": "⏸️ Пауза",
        "resume": "▶️ Продължи",
        "stop": "⏹️ Спри",
        "log_title": "Терминал в реално време:",
        "success_popup_title": "Свалянето завърши",
        "success_popup_msg": "🎉 Успех! Свалянето и конвертирането приключиха успешно!"
    },
    "Русский": {
        "title": "⬇️ Загрузчик YouTube",
        "subtitle": "Удобная загрузка высококачественного видео и аудио.",
        "url_label": "Ссылка YouTube (Видео, Плейлист или Аудио):",
        "url_placeholder": "...",
        "paste": "📋 Вставить",
        "copy": "📄 Копировать",
        "clear": "❌ Очистить",
        "autoclear": "Очищать ссылку после успешной загрузки",
        "analyze": "Анализировать",
        "analyzing": "Анализ...",
        "meta_title": "Информация о видео",
        "video_title": "Название:",
        "video_channel": "Канал:",
        "video_duration": "Длительность:",
        "no_video": "Нет (Введите ссылку и нажмите Анализировать)",
        "fetch_failed": "Не удалось загрузить данные видео.",
        "fetching": "Получение данных с YouTube...",
        "settings_title": "Настройки загрузки",
        "ffmpeg_active": "✅ FFmpeg: Активен (MP4/MP3 включены)",
        "ffmpeg_missing": "❌ FFmpeg: Отсутствует (Объединение MP3/MP4 отключено)",
        "quality_lbl": "Предпочитаемое качество:",
        "destination_lbl": "Папка для сохранения:",
        "browse": "Обзор...",
        "playlist_lbl": "Скачать весь плейлист (Пауза 10 сек. во избежание бана)",
        "show_log_lbl": "Показать терминал логов",
        "show_popup_lbl": "Показывать уведомление по завершении",
        "reset_defaults": "🔄 Сброс настроек",
        "start_download": "⚡ Начать загрузку",
        "downloading": "⏳ Загрузка...",
        "pause": "⏸️ Пауза",
        "resume": "▶️ Продолжить",
        "stop": "⏹️ Стоп",
        "log_title": "Терминал логов в реальном времени:",
        "success_popup_title": "Загрузка завершена",
        "success_popup_msg": "🎉 Успех! Загрузка и конвертация медиа завершены успешно!"
    },
    "Français": {
        "title": "⬇️ Téléchargeur YouTube",
        "subtitle": "Téléchargez des vidéos et des audios de haute qualité en toute fluidité.",
        "url_label": "URL YouTube (Vidéo, Liste ou Audio):",
        "url_placeholder": "...",
        "paste": "📋 Coller",
        "copy": "📄 Copier",
        "clear": "❌ Effacer",
        "autoclear": "Effacer l'URL après un téléchargement réussi",
        "analyze": "Analyser le lien",
        "analyzing": "Analyse en cours...",
        "meta_title": "Informations de la vidéo",
        "video_title": "Titre:",
        "video_channel": "Chaîne:",
        "video_duration": "Durée:",
        "no_video": "Aucun (Entrez une URL et cliquez sur Analyser)",
        "fetch_failed": "Impossible de récupérer les détails de la vidéo.",
        "fetching": "Récupération des détails depuis YouTube...",
        "settings_title": "Configuration du téléchargement",
        "ffmpeg_active": "✅ FFmpeg: Actif (MP4/MP3 activé)",
        "ffmpeg_missing": "❌ FFmpeg: Manquant (Fusion MP3/MP4 désactivée)",
        "quality_lbl": "Qualité préférée:",
        "destination_lbl": "Dossier de destination:",
        "browse": "Parcourir...",
        "playlist_lbl": "Télécharger toute la liste (Délai de 10s pour éviter le bannissement)",
        "show_log_lbl": "Afficher la console en direct",
        "show_popup_lbl": "Afficher une notification à la fin",
        "reset_defaults": "🔄 Réinitialiser les paramètres",
        "start_download": "⚡ Lancer le téléchargement",
        "downloading": "⏳ Téléchargement...",
        "pause": "⏸️ Pause",
        "resume": "▶️ Reprendre",
        "stop": "⏹️ Arrêter",
        "log_title": "Console de suivi en direct:",
        "success_popup_title": "Téléchargement terminé",
        "success_popup_msg": "🎉 Succès! Le téléchargement et la conversion ont été effectués correctement!"
    },
    "Italiano": {
        "title": "⬇️ Downloader YouTube",
        "subtitle": "Scarica video e audio di alta qualità senza interruzioni.",
        "url_label": "URL di YouTube (Video, Playlist o Audio):",
        "url_placeholder": "...",
        "paste": "📋 Incolla",
        "copy": "📄 Copia",
        "clear": "❌ Cancella",
        "autoclear": "Cancella URL dopo un download riuscito",
        "analyze": "Analizza Link",
        "analyzing": "Analisi in corso...",
        "meta_title": "Informazioni sul Video",
        "video_title": "Titolo:",
        "video_channel": "Canale:",
        "video_duration": "Durata:",
        "no_video": "Nessuno (Inserisci un URL e clicca su Analizza)",
        "fetch_failed": "Impossibile recuperare i dettagli del video.",
        "fetching": "Recupero dettagli da YouTube...",
        "settings_title": "Configurazione Download",
        "ffmpeg_active": "✅ FFmpeg: Attivo (MP4/MP3 Abilitato)",
        "ffmpeg_missing": "❌ FFmpeg: Mancante (Unione MP3/MP4 Disabilitata)",
        "quality_lbl": "Qualità preferita:",
        "destination_lbl": "Destinazione di salvataggio:",
        "browse": "Sfoglia...",
        "playlist_lbl": "Scarica intera playlist (Ritardo di 10s per evitare ban)",
        "show_log_lbl": "Mostra log terminale in tempo reale",
        "show_popup_lbl": "Mostra notifica al completamento",
        "reset_defaults": "🔄 Ripristina predefiniti",
        "start_download": "⚡ Avvia Download",
        "downloading": "⏳ Download in corso...",
        "pause": "⏸️ Pausa",
        "resume": "▶️ Riprendi",
        "stop": "⏹️ Interrompi",
        "log_title": "Terminale log in tempo reale:",
        "success_popup_title": "Download Completato",
        "success_popup_msg": "🎉 Successo! Il download e la conversione dei file multimediali sono stati completati correttamente!"
    },
    "Deutsch": {
        "title": "⬇️ YouTube-Downloader",
        "subtitle": "Videos und Audio nahtlos in hoher Qualität herunterladen.",
        "url_label": "YouTube-URL (Video, Playlist oder Audio):",
        "url_placeholder": "...",
        "paste": "📋 Einfügen",
        "copy": "📄 Kopieren",
        "clear": "❌ Löschen",
        "autoclear": "URL nach erfolgreichem Download automatisch leeren",
        "analyze": "Link analysieren",
        "analyzing": "Analysiere...",
        "meta_title": "Video-Informationen",
        "video_title": "Titel:",
        "video_channel": "Kanal:",
        "video_duration": "Dauer:",
        "no_video": "Keine (Geben Sie eine URL ein und klicken Sie auf Analysieren)",
        "fetch_failed": "Fehler beim Abrufen der Videodetails.",
        "fetching": "Abrufen der Details von YouTube...",
        "settings_title": "Download-Konfiguration",
        "ffmpeg_active": "✅ FFmpeg: Aktiv (MP4/MP3 aktiviert)",
        "ffmpeg_missing": "❌ FFmpeg: Fehlt (MP3/MP4-Zusammenführung deaktiviert)",
        "quality_lbl": "Bevorzugte Qualität:",
        "destination_lbl": "Speicherort:",
        "browse": "Durchsuchen...",
        "playlist_lbl": "Ganze Playlist herunterladen (10s Verzögerung gegen Sperrung)",
        "show_log_lbl": "Live-Protokollterminal anzeigen",
        "show_popup_lbl": "Popup-Benachrichtigung bei Fertigstellung anzeigen",
        "reset_defaults": "🔄 Standardeinstellungen zurücksetzen",
        "start_download": "⚡ Download starten",
        "downloading": "⏳ Herunterladen...",
        "pause": "⏸️ Pause",
        "resume": "▶️ Fortsetzen",
        "stop": "⏹️ Stopp",
        "log_title": "Live-Protokollterminal:",
        "success_popup_title": "Download abgeschlossen",
        "success_popup_msg": "🎉 Erfolg! Medien-Download & Konvertierung erfolgreich abgeschlossen!"
    },
    "Español": {
        "title": "⬇️ Descargador de YouTube",
        "subtitle": "Descarga videos y audio de alta calidad sin problemas.",
        "url_label": "URL de YouTube (Video, Lista o Audio):",
        "url_placeholder": "...",
        "paste": "📋 Pegar",
        "copy": "📄 Copiar",
        "clear": "❌ Limpiar",
        "autoclear": "Limpiar URL automáticamente tras la descarga",
        "analyze": "Analizar enlace",
        "analyzing": "Analizando...",
        "meta_title": "Información del Video",
        "video_title": "Título:",
        "video_channel": "Canal:",
        "video_duration": "Duración:",
        "no_video": "Ninguno (Introduce una URL y pulsa Analizar)",
        "fetch_failed": "Error al obtener detalles del video.",
        "fetching": "Obteniendo detalles de YouTube...",
        "settings_title": "Configuración de Descarga",
        "ffmpeg_active": "✅ FFmpeg: Activo (MP4/MP3 habilitado)",
        "ffmpeg_missing": "❌ FFmpeg: Faltante (Unión de MP3/MP4 deshabilitada)",
        "quality_lbl": "Calidad preferida:",
        "destination_lbl": "Destino de guardado:",
        "browse": "Buscar...",
        "playlist_lbl": "Descargar lista completa (Retraso de 10s para evitar bloqueo)",
        "show_log_lbl": "Mostrar registro en vivo",
        "show_popup_lbl": "Mostrar ventana emergente al finalizar",
        "reset_defaults": "🔄 Restablecer ajustes",
        "start_download": "⚡ Iniciar descarga",
        "downloading": "⏳ Descargando...",
        "pause": "⏸️ Pausar",
        "resume": "▶️ Reanudar",
        "stop": "⏹️ Detener",
        "log_title": "Terminal de registro en vivo:",
        "success_popup_title": "Descarga completada",
        "success_popup_msg": "🎉 ¡Éxito! La descarga y conversión multimedia han finalizado correctamente."
    },
    "日本語": {
        "title": "⬇️ YouTube ダウンローダー",
        "subtitle": "高品質の動画と音声をシームレスにダウンロードします。",
        "url_label": "YouTube URL (動画、プレイリスト、または音声):",
        "url_placeholder": "...",
        "paste": "📋 貼り付け",
        "copy": "📄 コピー",
        "clear": "❌ クリア",
        "autoclear": "ダウンロード完了後にURLを自動クリア",
        "analyze": "リンク分析",
        "analyzing": "分析中...",
        "meta_title": "動画情報",
        "video_title": "タイトル:",
        "video_channel": "チャンネル:",
        "video_duration": "再生時間:",
        "no_video": "なし (URLを入力して分析をクリック)",
        "fetch_failed": "動画情報の取得に失敗しました。",
        "fetching": "YouTubeから情報を取得中...",
        "settings_title": "ダウンロード設定",
        "ffmpeg_active": "✅ FFmpeg: 有効 (MP4/MP3 が有効)",
        "ffmpeg_missing": "❌ FFmpeg: 未検出 (MP3/MP4の結合が無効)",
        "quality_lbl": "優先品質:",
        "destination_lbl": "保存先フォルダ:",
        "browse": "参照...",
        "playlist_lbl": "プレイリスト全体を保存 (BAN防止のため10秒の間隔を空けます)",
        "show_log_lbl": "ログを表示する",
        "show_popup_lbl": "完了時にポップアップ通知を表示する",
        "reset_defaults": "🔄 設定の初期化",
        "start_download": "⚡ ダウンロード開始",
        "downloading": "⏳ ダウンロード中...",
        "pause": "⏸️ 一時停止",
        "resume": "▶️ 再開",
        "stop": "⏹️ 停止",
        "log_title": "リアルタイムログシステム:",
        "success_popup_title": "ダウンロード完了",
        "success_popup_msg": "🎉 成功しました！ファイルのダウンロードと変換が正常に完了しました。"
    },
    "한국어": {
        "title": "⬇️ YouTube 다운로더",
        "subtitle": "고품질 비디오 및 오디오를 원활하게 다운로드하세요.",
        "url_label": "YouTube URL (비디오, 재생 목록 또는 오디오):",
        "url_placeholder": "...",
        "paste": "📋 붙여넣기",
        "copy": "📄 복사",
        "clear": "❌ 지우기",
        "autoclear": "다운로드 완료 후 URL 자동 삭제",
        "analyze": "링크 분석",
        "analyzing": "분석 중...",
        "meta_title": "비디오 정보",
        "video_title": "제목:",
        "video_channel": "채널:",
        "video_duration": "길이:",
        "no_video": "없음 (URL 입력 후 분석 클릭)",
        "fetch_failed": "비디오 세부 정보를 가져오지 못했습니다.",
        "fetching": "YouTube에서 세부 정보 가져오는 중...",
        "settings_title": "다운로드 설정",
        "ffmpeg_active": "✅ FFmpeg: 활성화됨 (MP4/MP3 사용 가능)",
        "ffmpeg_missing": "❌ FFmpeg: 누락됨 (MP3/MP4 머징 비활성화됨)",
        "quality_lbl": "선호하는 화질:",
        "destination_lbl": "저장 경로:",
        "browse": "찾아보기...",
        "playlist_lbl": "재생 목록 전체 다운로드 (밴 방지를 위해 10초 대기 작동)",
        "show_log_lbl": "실시간 로그 터미널 표시",
        "show_popup_lbl": "완료 시 팝업 알림 표시",
        "reset_defaults": "🔄 기본값 복원",
        "start_download": "⚡ 다운로드 시작",
        "downloading": "⏳ 다운로드 중...",
        "pause": "⏸️ 일시 정지",
        "resume": "▶️ 다시 시작",
        "stop": "⏹️ 중지",
        "log_title": "실시간 로그 터미널:",
        "success_popup_title": "다운로드 완료",
        "success_popup_msg": "🎉 성공! 미디어 다운로드 및 변환이 정상적으로 완료되었습니다!"
    },
    "简体中文": {
        "title": "⬇️ YouTube 下载器",
        "subtitle": "无缝下载高品质视频和音频资源。",
        "url_label": "YouTube 链接 (视频、播放列表或音频):",
        "url_placeholder": "...",
        "paste": "📋 粘贴",
        "copy": "📄 复制",
        "clear": "❌ 清除",
        "autoclear": "下载成功后自动清除链接",
        "analyze": "分析链接",
        "analyzing": "正在分析...",
        "meta_title": "视频信息",
        "video_title": "标题:",
        "video_channel": "频道:",
        "video_duration": "时长:",
        "no_video": "无 (请输入链接并点击分析)",
        "fetch_failed": "无法获取视频详细信息。",
        "fetching": "正在从 YouTube 获取详细信息...",
        "settings_title": "下载配置",
        "ffmpeg_active": "✅ FFmpeg: 已启用 (支持 MP4/MP3 合成)",
        "ffmpeg_missing": "❌ FFmpeg: 未检测到 (MP3/MP4 合并已禁用)",
        "quality_lbl": "首选质量:",
        "destination_lbl": "保存路径:",
        "browse": "浏览...",
        "playlist_lbl": "下载整个播放列表 (自动添加 10 秒延迟防封禁)",
        "show_log_lbl": "显示实时日志终端",
        "show_popup_lbl": "完成时弹出通知提示",
        "reset_defaults": "🔄 重置默认设置",
        "start_download": "⚡ 开始下载",
        "downloading": "⏳ 正在下载...",
        "pause": "⏸️ 暂停",
        "resume": "▶️ 继续",
        "stop": "⏹️ 停止",
        "log_title": "实时日志终端:",
        "success_popup_title": "下载完成",
        "success_popup_msg": "🎉 成功！媒体下载和格式转换已顺利完成！"
    },
    "हिन्दी": {
        "title": "⬇️ यूट्यूब डाउनलोडर",
        "subtitle": "उच्च गुणवत्ता वाले वीडियो और ऑडियो को आसानी से डाउनलोड करें।",
        "url_label": "यूट्यूब URL (वीडियो, प्लेलिस्ट, या ऑडियो):",
        "url_placeholder": "...",
        "paste": "📋 पेस्ट करें",
        "copy": "📄 कॉपी करें",
        "clear": "❌ साफ करें",
        "autoclear": "सफल डाउनलोड के बाद लिंक को अपने आप हटाएं",
        "analyze": "लिंक का विश्लेषण करें",
        "analyzing": "विश्लेषण किया जा रहा है...",
        "meta_title": "वीडियो की जानकारी",
        "video_title": "शीर्षक:",
        "video_channel": "चैनल:",
        "video_duration": "अवधि:",
        "no_video": "कोई नहीं (कृपया URL दर्ज करें और विश्लेषण पर क्लिक करें)",
        "fetch_failed": "वीडियो की जानकारी प्राप्त करने में विफल।",
        "fetching": "यूट्यूब से जानकारी प्राप्त की जा रही है...",
        "settings_title": "डाउनलोड कॉन्फ़िगरेशन",
        "ffmpeg_active": "✅ FFmpeg: सक्रिय है (MP4/MP3 सक्षम)",
        "ffmpeg_missing": "❌ FFmpeg: अनुपलब्ध (MP3/MP4 मर्जिंग अक्षम)",
        "quality_lbl": "पसंदीदा गुणवत्ता:",
        "destination_lbl": "सुरक्षित करने का स्थान:",
        "browse": "ब्राउज़ करें...",
        "playlist_lbl": "पूरी प्लेलिस्ट डाउनलोड करें (प्रतिबंध से बचने के लिए 10 सेकंड की देरी)",
        "show_log_lbl": "लाइव लॉग टर्मिनल दिखाएं",
        "show_popup_lbl": "समाप्ति पर पॉपअप सूचना दिखाएं",
        "reset_defaults": "🔄 डिफ़ॉल्ट रीसेट करें",
        "start_download": "⚡ डाउनलोड शुरू करें",
        "downloading": "⏳ डाउनलोड हो रहा है...",
        "pause": "⏸️ रोकें",
        "resume": "▶️ फिर से शुरू करें",
        "stop": "⏹️ बंद करें",
        "log_title": "लाइव लॉग टर्मिनल:",
        "success_popup_title": "डाउनलोड पूरा हुआ",
        "success_popup_msg": "🎉 बधाई! मीडिया डाउनलोड और रूपांतरण सफलतापूर्वक पूरा हो गया है!"
    }
}